name = "distillpub"
license = "MIT"
licenselink = "https://github.com/activatedgeek/distillpub/blob/master/LICENSE"
description = "Hugo theme for Distill articles"
homepage = "https://github.com/activatedgeek/distillpub"
tags = []
features = []
min_version = "0.55"

[author]
  name = "Sanyam Kapoor"
  homepage = "https://www.sanyamkapoor.com"
