baseUrl = ""
title = "Distill Hugo Theme"
author = "Sanyam Kapoor"
canonifyurls = true
theme = "distillpub"

[params]
  description = "Distill Hugo Theme Demo"
  keywords = ["hugo", "distill", "theme"]
  sourcePrefix = "https://github.com/activatedgeek/distillpub/blob/master/exampleSite"

  color = "#0f2e3d"

  [params.social]
  "a.fab.fa-google" = "https://scholar.google.com/citations?user=p0NMtgsAAAAJ"
  "b.fab.fa-github" = "https://github.com/activatedgeek/distillpub"
  "c.fab.fa-hacker-news" = "https://news.ycombinator.com/user?id=activatedgeek"
  "d.fab.fa-linkedin" = "https://linkedin.com/in/sanyamkapoor"
  "e.fab.fa-stack-overflow" = "https://stackoverflow.com/users/2425365"
  "f.fab.fa-twitter" = "https://twitter.com/activatedgeek"

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About Hugo"
  title = "about"
  url = "/about"
  weight = -10
