baseUrl = ""
title = "Distill Hugo Theme"
author = "Sanyam Kapoor"
canonifyurls = true
paginate = 3
theme = "distillpub"

[params]
    description = "Distill Hugo Theme Demo"
    keywords = ["hugo", "distill", "theme"]
